name: absensipkl
description: "Aplikasi presentasi"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  dio: ^5.4.3+1
  either_dart: ^1.0.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_dotenv: ^5.1.0
  flutter_riverpod: ^2.5.1
  fluttertoast: ^8.2.5
  freezed_annotation: ^2.4.1
  get_storage: ^2.1.1
  google_fonts: ^6.2.1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  riverpod_annotation: ^2.3.5
  toastification: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.9
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  freezed: ^2.5.2
  json_serializable: ^6.8.0

flutter:

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Bold.ttf
        - asset: fonts/Roboto-Italic.ttf
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Medium.ttf
        - asset: fonts/Roboto-Light.ttf

  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/gif/
